# Generated by Django 3.2.7 on 2021-10-01 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
        ('students', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='students',
            field=models.ManyToManyField(to='students.Student'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='supervising_teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher'),
        ),
    ]
