# Generated by Django 3.2.7 on 2021-10-06 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20211006_1158'),
        ('classes', '0004_mark_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='teachers',
            field=models.ManyToManyField(related_name='teachers', to='teachers.Teacher'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='supervising_teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='supervising_teacher', to='teachers.teacher'),
        ),
    ]
