# Generated by Django 3.2.7 on 2021-10-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20211006_1158'),
        ('classes', '0005_auto_20211006_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(to='teachers.Teacher'),
        ),
    ]
