# Generated by Django 3.2.7 on 2021-09-30 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('names', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('place_of_birth', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('school_class', models.CharField(max_length=10)),
                ('contact_number', models.CharField(max_length=9)),
                ('profile_pic', models.ImageField(default='profile_pic/def_profile_pic.jpeg', upload_to='profile_pic/')),
                ('subjects', models.ManyToManyField(to='school.Subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('weight', models.FloatField(max_length=3)),
                ('note', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subject')),
            ],
        ),
    ]
