# Generated by Django 3.2.7 on 2021-09-29 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('names', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('place_of_birth', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('school_class', models.CharField(max_length=10)),
                ('contact_number', models.CharField(max_length=12)),
                ('profile_pic', models.ImageField(blank=True, default='def_profile_pic.jpg', upload_to='profile_pic/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
