# Generated by Django 3.2.7 on 2021-10-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'permissions': [('special_status', 'Can view students list and edit marks'), ('is_teacher', 'Can view teacher home page')]},
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_pic',
            field=models.ImageField(default='profile_pic/def_profile_pic.jpeg', upload_to='profile_pic/'),
        ),
    ]
